feat(update-team): creating update team mutation
budproj/business pull request #199
Opened 2022-07-26 18:27 UTC by rodrigoantas

## 🎢 Motivation

A brief summary of the purpose of this PR.

## 🔧 Solution

How the implementation works or fixes the issue.

## 🚨  Testing

A brief description of how the reviewer can test my PR.

## 🃏 Task Card

Link to issue on Jira

- [`BUD22-123`](https://)

## 🔗 Related PRs

This PR is related to some other PRs in different services, they are:

- [`project#PR_NUMBER`](https://)

## 🍩 Validation

Who tested this PR?

### Canary

- [ ] Marcelo
- [ ] Gustavo
- [ ] Aline

### Dev

- [ ] Perin
- [ ] Guilherme
- [ ] Rodrigo
- [ ] Diego

2022-07-27 13:35 UTC, diegomagalhaes-dev approved these changes

2022-07-27 13:59 UTC, guiluchesi commented
@rodrigoantas outra coisa, cara, agora a gente tem esse template bonitão, vamos tentar manter a documentação preenchida sempre que possível. Talvez tenha campos que não faça sentido e ai pode só apagar esses trechos.

2022-07-27 14:15 UTC, guiluchesi requested changes
@rodrigoantas outra coisa, cara, agora a gente tem esse template bonitão, vamos tentar manter a documentação preenchida sempre que possível. Talvez tenha campos que não faça sentido e ai pode só apagar esses trechos.

2022-07-28 14:07 UTC, rodrigoantas commented on src/interface/graphql/modules/team/team.access-control.ts
> +  isSameUser(user: UserWithContext, team: Team): boolean {
tens razão!

2022-07-28 14:19 UTC, rodrigoantas commented
> @rodrigoantas outra coisa, cara, agora a gente tem esse template bonitão, vamos tentar manter a documentação preenchida sempre que possível. Talvez tenha campos que não faça sentido e ai pode só apagar esses trechos.

2022-07-28 16:16 UTC, guiluchesi approved these changes
Coisa linda de ver!

2022-07-28 16:16 UTC, merged